name: Update Fuel Prices

on:
  schedule:
    - cron: '0 6 * * *' # Exécution tous les jours à 6h du matin
  workflow_dispatch: # Permet de le lancer manuellement depuis GitHub

jobs:
  update-fuel:
    runs-on: ubuntu-latest
    
    # AJOUTER CETTE SECTION PERMISSIONS :
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build project
        run: npm run build

      - name: Commit and push changes (si nécessaire)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automatic build check"
          branch: main
